### ISSUE TITLE
stack new doesn't work

### ISSUE THREAD

**Issue by AlexGoico** [freebroccolo/docker-haskell#71]
Creating a new haskell stack project fails to work.

Example Command:
```
docker run --rm -v $PWD:/my_app -w /my_app haskell:8 stack new app new-template
```

Fails with the following error:
```
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

Googling seems to suggest a stack upgrade command is required:
https://github.com/fpco/stackage/issues/2759

In addition, assuming the Dockerfile does get patched this yields yet another error when `stack build`ing.
```
The following executables are missing and must be installed: xz, make
```
Thus perhaps these also need to be added to the Dockerfiles for stack support

**Comment by magbicaleman** [comment]
I ran `stack upgrade` which updates to `1.7.1`, but then it needs to download `ghc-8.2.2`, which defeats the purpose of the image.

**Comment by psftw** [comment]
Correct, the version of Stack that we ship with the image has gotten behind causing a few issues.  We will be shipping the latest Stack (1.7.1) and GHC (8.4.2) soon.  Even in the new image, there will still be a temporary issue with "stack new" since the default Stackage resolver won't match the GHC release in the image, but you can explicitly set your resolver to one which matches your GHC version (i.e. `ghc-8.4.2`).  Will double check to make sure xz and make are included (thanks!).
Closing this as the next release will include fixes for Stack support
