### ISSUE TITLE
None of the examples work

### ISSUE THREAD

**Issue by Risto-Stevcev** [freebroccolo/docker-haskell#96]
First example
```dockerfile
FROM haskell:8
RUN stack install pandoc pandoc-citeproc
ENTRYPOINT ["pandoc"]
```
Gives:
```sh
miniarch% docker build -t pandoc .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM haskell:8
 ---> d0f33c86f706
Step 2/3 : RUN stack install pandoc pandoc-citeproc
 ---> Running in ac6d2e2512c3
Writing implicit global project config file to: /root/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-14.7
No compiler found, expected minor version match with ghc-8.6.5 (x86_64) (based on resolver setting in /root/.stack/global-project/stack.yaml).
To install the correct GHC into /root/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
The command '/bin/sh -c stack install pandoc pandoc-citeproc' returned a non-zero code: 1
```

And the second example
```dockerfile
FROM haskell:8
RUN cabal update && cabal install pandoc pandoc-citeproc
ENTRYPOINT ["pandoc"]
```

Gives:
```sh
miniarch% docker build -t pandoc .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM haskell:8
 ---> d0f33c86f706
Step 2/3 : RUN cabal update && cabal install pandoc pandoc-citeproc
 ---> Running in 925b3c46cf3f
Config file path source is default config file.
Config file /root/.cabal/config not found.
Writing default configuration to /root/.cabal/config
Downloading the latest package list from hackage.haskell.org
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.7.3 (user goal)
[__1] trying: http-client-tls-0.3.5.3 (dependency of pandoc)
[__2] trying: tls-1.5.1 (dependency of http-client-tls)
[__3] trying: x509-validation-1.6.11 (dependency of tls)
[__4] trying: asn1-encoding-0.9.5 (dependency of tls)
[__5] next goal: base (dependency of pandoc)
[__5] rejecting: base-4.13.0.0/installed-4.1... (conflict: asn1-encoding =>
base>=3 && <4.13)
[__5] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__5] fail (backjumping, conflict set: asn1-encoding, base, pandoc)
Backjump limit reached (currently 4000, change with --max-backjumps or try to
run with --reorder-goals).

The command '/bin/sh -c cabal update && cabal install pandoc pandoc-citeproc' returned a non-zero code: 1
```

**Comment by psftw** [comment]
We can definitely do better with the examples, but both of these issues are caused by the latest 8.8.1 release and are expected.  The first issue is covered in the documentation ( https://github.com/docker-library/docs/tree/master/haskell#considerations-for-stack ) and the second issue looks like a dependency problem in the upstream project. When a new version of GHC is released, library maintainers need to update their dependencies based on the new versions of libraries bundled with GHC itself. This can happen before or after a GHC release. In this case it looks like the package wants base < 4.13, but GHC 8.8.1 ships with 4.13. As part of testing the 8.8.1 image before releasing it, I did see that pandoc installs fine on 8.6.5 but encounters the error you see for 8.8.1.  There are a number of packages in this state, which will naturally resolve itself over time. Once Stack has an 8.8.1-based LTS resolver, things will settle down for a while until the next release. Hope this helps.

**Comment by Risto-Stevcev** [comment]
How can I get it to work? I'm looking for a reliable way to use haskell applications, I wanted to use `pandoc` for something but it just craps if I try to install with `pacman`, and I've had issues with globally installing stack because it's not a package manager. I was hoping a docker container would do the trick

Is there a way to freeze the stack resolver so that the docker container always works? I've used haskell on and off quite a lot but this always becomes a huge pain point for me and it's forced me to pretty much stop using any haskell apps like `xmonad` or `pandoc` (and recently `hedgewars`). I've heard of people switching to nix but I haven't had the time to learn it yet

**Comment by psftw** [comment]
> I did see that pandoc installs fine on 8.6.5

Something like this should work:
```
FROM haskell:8.6.5
RUN cabal new-update && cabal new-install pandoc
```
